/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.views;

import java.text.ParseException;
import javax.swing.JOptionPane;
import model.entities.Cliente;
import model.entities.ItemDePedido;
import model.entities.Pedido;
import model.services.FabricaItensDePedido;
import model.services.GeradorComanda;

/**
 *
 * @author marcos
 */
public class TelaCardapio extends javax.swing.JFrame {

    /**
     * Creates new form TelaCardapio
     */
    private Pedido pedidoAtual;

    public TelaCardapio(Cliente cliente) {
        initComponents();
        pedidoAtual = new Pedido(cliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlsLista = new javax.swing.JList<>();
        encerrarCompra = new javax.swing.JButton();
        verCarrinho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cardápio");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.gray);
        setIconImages(null);

        jlsLista.setBackground(new java.awt.Color(238, 238, 238));
        jlsLista.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jlsLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "teste" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlsLista.setToolTipText("");
        jlsLista.setSelectionBackground(new java.awt.Color(51, 255, 0));
        jlsLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlsListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlsLista);

        encerrarCompra.setText("Encerrar Compra");
        encerrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarCompraActionPerformed(evt);
            }
        });

        verCarrinho.setText("Ver Carrinho");
        verCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encerrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encerrarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verCarrinho)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlsListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlsListaValueChanged
        String numeroDeProdutos = JOptionPane.showInputDialog("Informe a quantidade de Itens");
        if ((numeroDeProdutos.matches("[0-9]*")) || (numeroDeProdutos == null)) {
            int quantidade = Integer.parseInt(numeroDeProdutos);
            ItemDePedido ordem = FabricaItensDePedido.gerarItemDePedido(this.jlsLista.getSelectedValue(), quantidade);
            int decisao = JOptionPane.showConfirmDialog(null, ordem, "Adiconar", 0);
            final int ESCOLHEU_SIM = 0;
            if (decisao == ESCOLHEU_SIM) {
                pedidoAtual.addItem(ordem);
            } else {
                JOptionPane.showMessageDialog(null, "Produto Descartado", "Informação", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Valor não numérico", "Erro", 0);
        }

    }//GEN-LAST:event_jlsListaValueChanged

    private void encerrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarCompraActionPerformed
        pedidoAtual.comprar();
        String notaFiscal = GeradorComanda.geradorNotaFiscal(pedidoAtual);
        JOptionPane.showMessageDialog(null, notaFiscal);
        GeradorComanda.gerarEmail(notaFiscal);
        GeradorComanda.gerarLog(notaFiscal);
        JOptionPane.showMessageDialog(null, "Obrigado pela Preferência\nO tempo estimado é de 2 horas");
        System.exit(0);

    }//GEN-LAST:event_encerrarCompraActionPerformed

    private void verCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCarrinhoActionPerformed
        String carrinho = "";
        for (ItemDePedido ordem : pedidoAtual.getItemDePedido()) {
            carrinho += ordem + "\n-------------------------\n";
        }
        carrinho += "\nSubtotal: R$" + pedidoAtual.valorTotal();
        JOptionPane.showMessageDialog(null, carrinho, "Carrinho", 1);
    }//GEN-LAST:event_verCarrinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCardapio(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encerrarCompra;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JList<String> jlsLista;
    private javax.swing.JButton verCarrinho;
    // End of variables declaration//GEN-END:variables
}
